# tests/test_local.py — Terminal chat simulator
# Generated by AgentKit

"""
Test your agent without needing WhatsApp.
Simulates a conversation in the terminal.
"""

import asyncio
import sys
import os

# Add the project root to the path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from agent.brain import generate_reply
from agent.memory import init_db, save_message, get_history, clear_history

TEST_PHONE = "test-local-001"


async def main():
    """Main loop of the test chat."""
    await init_db()

    print()
    print("=" * 55)
    print("   AgentKit — Local Test")
    print("=" * 55)
    print()
    print("  Type messages as if you were a customer.")
    print("  Special commands:")
    print("    'clear'  — wipe the history")
    print("    'exit'   — end the test")
    print()
    print("-" * 55)
    print()

    while True:
        try:
            message = input("You: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\n\nTest finished.")
            break

        if not message:
            continue

        if message.lower() == "exit":
            print("\nTest finished.")
            break

        if message.lower() == "clear":
            await clear_history(TEST_PHONE)
            print("[History cleared]\n")
            continue

        # Get history BEFORE saving (brain.py appends the current message)
        history = await get_history(TEST_PHONE)

        # Generate reply
        print("\nAgent: ", end="", flush=True)
        reply = await generate_reply(message, history)
        print(reply)
        print()

        # Save the user's message and the agent's reply
        await save_message(TEST_PHONE, "user", message)
        await save_message(TEST_PHONE, "assistant", reply)


if __name__ == "__main__":
    asyncio.run(main())
