# tests/test_local.py — Terminal chat simulator
# Generated by AgentKit

"""
Test your agent without needing WhatsApp.
Simulates a conversation in the terminal.
"""

import asyncio
import sys
import os

# Add the project root to the path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from agent.brain import generar_respuesta
from agent.memory import inicializar_db, guardar_mensaje, obtener_historial, limpiar_historial

TELEFONO_TEST = "test-local-001"


async def main():
    """Main loop of the test chat."""
    await inicializar_db()

    print()
    print("=" * 55)
    print("   AgentKit — Local Test")
    print("=" * 55)
    print()
    print("  Type messages as if you were a customer.")
    print("  Special commands:")
    print("    'clear'  — wipe the history")
    print("    'exit'   — end the test")
    print()
    print("-" * 55)
    print()

    while True:
        try:
            mensaje = input("You: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\n\nTest finished.")
            break

        if not mensaje:
            continue

        if mensaje.lower() == "exit":
            print("\nTest finished.")
            break

        if mensaje.lower() == "clear":
            await limpiar_historial(TELEFONO_TEST)
            print("[History cleared]\n")
            continue

        # Get history BEFORE saving (brain.py appends the current message)
        historial = await obtener_historial(TELEFONO_TEST)

        # Generate reply
        print("\nAgent: ", end="", flush=True)
        respuesta = await generar_respuesta(mensaje, historial)
        print(respuesta)
        print()

        # Save the user's message and the agent's reply
        await guardar_mensaje(TELEFONO_TEST, "user", mensaje)
        await guardar_mensaje(TELEFONO_TEST, "assistant", respuesta)


if __name__ == "__main__":
    asyncio.run(main())
