# agent/providers/__init__.py — Provider factory
# Generated by AgentKit

"""
Picks the WhatsApp provider based on the WHATSAPP_PROVIDER variable in .env.
"""

import os
from agent.providers.base import WhatsAppProvider


def get_provider() -> WhatsAppProvider:
    """Return the WhatsApp provider configured in .env."""
    provider = os.getenv("WHATSAPP_PROVIDER", "").lower()

    if not provider:
        raise ValueError("WHATSAPP_PROVIDER not set in .env. Use: meta or twilio")

    if provider == "meta":
        from agent.providers.meta import MetaProvider
        return MetaProvider()
    elif provider == "twilio":
        from agent.providers.twilio import TwilioProvider
        return TwilioProvider()
    else:
        raise ValueError(f"Unsupported provider: {provider}. Use: meta or twilio")
