# agent/providers/__init__.py — Provider factory
# Generated by AgentKit

"""
Picks the WhatsApp provider based on the WHATSAPP_PROVIDER variable in .env.
"""

import os
from agent.providers.base import ProveedorWhatsApp


def obtener_proveedor() -> ProveedorWhatsApp:
    """Return the WhatsApp provider configured in .env."""
    proveedor = os.getenv("WHATSAPP_PROVIDER", "").lower()

    if not proveedor:
        raise ValueError("WHATSAPP_PROVIDER not set in .env. Use: meta or twilio")

    if proveedor == "meta":
        from agent.providers.meta import ProveedorMeta
        return ProveedorMeta()
    elif proveedor == "twilio":
        from agent.providers.twilio import ProveedorTwilio
        return ProveedorTwilio()
    else:
        raise ValueError(f"Unsupported provider: {proveedor}. Use: meta or twilio")
