# agent/providers/base.py — Base class for WhatsApp providers
# Generated by AgentKit

"""
Defines the common interface every WhatsApp provider must implement.
This lets us swap providers without touching the rest of the code.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from fastapi import Request


@dataclass
class IncomingMessage:
    """Normalized message — same shape no matter the provider."""
    phone: str          # Sender's phone number
    text: str           # Message content
    message_id: str     # Unique message ID
    is_own: bool        # True if the agent sent it (ignored)


class WhatsAppProvider(ABC):
    """Interface every WhatsApp provider must implement."""

    @abstractmethod
    async def parse_webhook(self, request: Request) -> list[IncomingMessage]:
        """Extract and normalize messages from the webhook payload."""
        ...

    @abstractmethod
    async def send_message(self, phone: str, message: str) -> bool:
        """Send a text message. Returns True on success."""
        ...

    async def validate_webhook(self, request: Request) -> dict | int | None:
        """GET webhook verification (only Meta needs it). Returns a response or None."""
        return None
