# agent/providers/base.py — Base class for WhatsApp providers
# Generated by AgentKit

"""
Defines the common interface every WhatsApp provider must implement.
This lets us swap providers without touching the rest of the code.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from fastapi import Request


@dataclass
class MensajeEntrante:
    """Normalized message — same shape no matter the provider."""
    telefono: str       # Sender's phone number
    texto: str          # Message content
    mensaje_id: str     # Unique message ID
    es_propio: bool     # True if the agent sent it (ignored)


class ProveedorWhatsApp(ABC):
    """Interface every WhatsApp provider must implement."""

    @abstractmethod
    async def parsear_webhook(self, request: Request) -> list[MensajeEntrante]:
        """Extract and normalize messages from the webhook payload."""
        ...

    @abstractmethod
    async def enviar_mensaje(self, telefono: str, mensaje: str) -> bool:
        """Send a text message. Returns True on success."""
        ...

    async def validar_webhook(self, request: Request) -> dict | int | None:
        """GET webhook verification (only Meta needs it). Returns a response or None."""
        return None
