# agent/providers/twilio.py — Adapter for Twilio WhatsApp
# Generated by AgentKit

import os
import logging
import base64
import httpx
from fastapi import Request
from agent.providers.base import WhatsAppProvider, IncomingMessage

logger = logging.getLogger("agentkit")


class TwilioProvider(WhatsAppProvider):
    """WhatsApp provider using Twilio."""

    def __init__(self):
        self.account_sid = os.getenv("TWILIO_ACCOUNT_SID")
        self.auth_token = os.getenv("TWILIO_AUTH_TOKEN")
        self.phone_number = os.getenv("TWILIO_PHONE_NUMBER")

    async def parse_webhook(self, request: Request) -> list[IncomingMessage]:
        """Parse Twilio's form-encoded payload."""
        form = await request.form()
        text = form.get("Body", "")
        phone = form.get("From", "").replace("whatsapp:", "")
        message_id = form.get("MessageSid", "")
        if not text:
            return []
        return [IncomingMessage(
            phone=phone,
            text=text,
            message_id=message_id,
            is_own=False,
        )]

    async def send_message(self, phone: str, message: str) -> bool:
        """Send a message via the Twilio API."""
        if not all([self.account_sid, self.auth_token, self.phone_number]):
            logger.warning("Twilio variables not configured")
            return False
        url = f"https://api.twilio.com/2010-04-01/Accounts/{self.account_sid}/Messages.json"
        auth = base64.b64encode(f"{self.account_sid}:{self.auth_token}".encode()).decode()
        headers = {"Authorization": f"Basic {auth}"}
        data = {
            "From": f"whatsapp:{self.phone_number}",
            "To": f"whatsapp:{phone}",
            "Body": message,
        }
        async with httpx.AsyncClient() as client:
            r = await client.post(url, data=data, headers=headers)
            if r.status_code != 201:
                logger.error(f"Twilio error: {r.status_code} — {r.text}")
            return r.status_code == 201
