# agent/brain.py — The agent's brain: connection to the OpenAI API
# Generated by AgentKit (configured to use OpenAI gpt-4o-mini)

"""
The agent's AI logic. Reads the system prompt from prompts.yaml
and generates replies using the OpenAI Chat Completions API.
"""

import os
import yaml
import logging
from openai import AsyncOpenAI
from dotenv import load_dotenv

load_dotenv()
logger = logging.getLogger("agentkit")

# OpenAI client (base_url lets you point at OpenAI or a compatible endpoint)
client = AsyncOpenAI(
    api_key=os.getenv("OPENAI_API_KEY"),
    base_url=os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1"),
)

# Generation model, configurable from .env
GENERATION_MODEL_ID = os.getenv("GENERATION_MODEL_ID", "gpt-4o-mini")


def cargar_config_prompts() -> dict:
    """Read the whole configuration from config/prompts.yaml."""
    try:
        with open("config/prompts.yaml", "r", encoding="utf-8") as f:
            return yaml.safe_load(f) or {}
    except FileNotFoundError:
        logger.error("config/prompts.yaml not found")
        return {}


def cargar_system_prompt() -> str:
    """Read the system prompt from config/prompts.yaml."""
    config = cargar_config_prompts()
    return config.get("system_prompt", "You are a helpful assistant. Respond in English.")


def obtener_mensaje_error() -> str:
    """Return the error message configured in prompts.yaml."""
    config = cargar_config_prompts()
    return config.get("error_message", "Sorry, I'm having technical trouble. Please try again in a few minutes.")


def obtener_mensaje_fallback() -> str:
    """Return the fallback message configured in prompts.yaml."""
    config = cargar_config_prompts()
    return config.get("fallback_message", "Sorry, I didn't catch that. Could you rephrase it?")


async def generar_respuesta(mensaje: str, historial: list[dict]) -> str:
    """
    Generate a reply using the OpenAI Chat Completions API.

    Args:
        mensaje: The user's new message
        historial: List of previous messages [{"role": "user/assistant", "content": "..."}]

    Returns:
        The reply generated by the model
    """
    # If the message is too short or empty, use the fallback
    if not mensaje or len(mensaje.strip()) < 2:
        return obtener_mensaje_fallback()

    system_prompt = cargar_system_prompt()

    # Build the messages list for the API.
    # OpenAI takes the system prompt as the first message (role "system").
    mensajes = [{"role": "system", "content": system_prompt}]
    for msg in historial:
        mensajes.append({
            "role": msg["role"],
            "content": msg["content"]
        })

    # Append the current message
    mensajes.append({
        "role": "user",
        "content": mensaje
    })

    try:
        response = await client.chat.completions.create(
            model=GENERATION_MODEL_ID,
            max_tokens=1024,
            messages=mensajes
        )

        respuesta = response.choices[0].message.content
        usage = response.usage
        if usage:
            logger.info(f"Reply generated ({usage.prompt_tokens} in / {usage.completion_tokens} out)")
        return respuesta

    except Exception as e:
        logger.error(f"OpenAI API error: {e}")
        return obtener_mensaje_error()
