# agent/brain.py — The agent's brain: connection to the OpenAI API
# Generated by AgentKit (configured to use OpenAI gpt-4o-mini)

"""
The agent's AI logic. Reads the system prompt from prompts.yaml
and generates replies using the OpenAI Chat Completions API.
"""

import os
import yaml
import logging
from openai import AsyncOpenAI
from dotenv import load_dotenv

load_dotenv()
logger = logging.getLogger("agentkit")

# OpenAI client (base_url lets you point at OpenAI or a compatible endpoint)
client = AsyncOpenAI(
    api_key=os.getenv("OPENAI_API_KEY"),
    base_url=os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1"),
)

# Generation model, configurable from .env
GENERATION_MODEL_ID = os.getenv("GENERATION_MODEL_ID", "gpt-4o-mini")


def load_prompts_config() -> dict:
    """Read the whole configuration from config/prompts.yaml."""
    try:
        with open("config/prompts.yaml", "r", encoding="utf-8") as f:
            return yaml.safe_load(f) or {}
    except FileNotFoundError:
        logger.error("config/prompts.yaml not found")
        return {}


def load_system_prompt() -> str:
    """Read the system prompt from config/prompts.yaml."""
    config = load_prompts_config()
    return config.get("system_prompt", "You are a helpful assistant. Respond in English.")


def get_error_message() -> str:
    """Return the error message configured in prompts.yaml."""
    config = load_prompts_config()
    return config.get("error_message", "Sorry, I'm having technical trouble. Please try again in a few minutes.")


def get_fallback_message() -> str:
    """Return the fallback message configured in prompts.yaml."""
    config = load_prompts_config()
    return config.get("fallback_message", "Sorry, I didn't catch that. Could you rephrase it?")


async def generate_reply(message: str, history: list[dict]) -> str:
    """
    Generate a reply using the OpenAI Chat Completions API.

    Args:
        message: The user's new message
        history: List of previous messages [{"role": "user/assistant", "content": "..."}]

    Returns:
        The reply generated by the model
    """
    # If the message is too short or empty, use the fallback
    if not message or len(message.strip()) < 2:
        return get_fallback_message()

    system_prompt = load_system_prompt()

    # Build the messages list for the API.
    # OpenAI takes the system prompt as the first message (role "system").
    messages = [{"role": "system", "content": system_prompt}]
    for msg in history:
        messages.append({
            "role": msg["role"],
            "content": msg["content"]
        })

    # Append the current message
    messages.append({
        "role": "user",
        "content": message
    })

    try:
        response = await client.chat.completions.create(
            model=GENERATION_MODEL_ID,
            max_tokens=1024,
            messages=messages
        )

        reply = response.choices[0].message.content
        usage = response.usage
        if usage:
            logger.info(f"Reply generated ({usage.prompt_tokens} in / {usage.completion_tokens} out)")
        return reply

    except Exception as e:
        logger.error(f"OpenAI API error: {e}")
        return get_error_message()
