# agent/main.py — FastAPI server + WhatsApp webhook
# Generated by AgentKit

"""
Main server for the WhatsApp agent.
Works with any provider (Meta, Twilio) thanks to the providers layer.
"""

import os
import logging
from contextlib import asynccontextmanager
from fastapi import FastAPI, Request, HTTPException
from fastapi.responses import PlainTextResponse
from dotenv import load_dotenv

from agent.brain import generar_respuesta
from agent.memory import inicializar_db, guardar_mensaje, obtener_historial
from agent.providers import obtener_proveedor

load_dotenv()

# Logging configuration depending on environment
ENVIRONMENT = os.getenv("ENVIRONMENT", "development")
log_level = logging.DEBUG if ENVIRONMENT == "development" else logging.INFO
logging.basicConfig(level=log_level)
logger = logging.getLogger("agentkit")

# WhatsApp provider (configured in .env via WHATSAPP_PROVIDER)
proveedor = obtener_proveedor()
PORT = int(os.getenv("PORT", 8000))


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Initialize the database when the server starts."""
    await inicializar_db()
    logger.info("Database initialized")
    logger.info(f"AgentKit server running on port {PORT}")
    logger.info(f"WhatsApp provider: {proveedor.__class__.__name__}")
    yield


app = FastAPI(
    title="AgentKit — WhatsApp AI Agent",
    version="1.0.0",
    lifespan=lifespan
)


@app.get("/")
async def health_check():
    """Health endpoint for Railway/monitoring."""
    return {"status": "ok", "service": "agentkit"}


@app.get("/webhook")
async def webhook_verificacion(request: Request):
    """GET webhook verification (required by Meta Cloud API, no-op for others)."""
    resultado = await proveedor.validar_webhook(request)
    if resultado is not None:
        return PlainTextResponse(str(resultado))
    return {"status": "ok"}


@app.post("/webhook")
async def webhook_handler(request: Request):
    """
    Receives WhatsApp messages via the configured provider.
    Processes the message, generates a reply with Claude, and sends it back.
    """
    try:
        # Parse webhook — the provider normalizes the format
        mensajes = await proveedor.parsear_webhook(request)

        for msg in mensajes:
            # Ignore own or empty messages
            if msg.es_propio or not msg.texto:
                continue

            logger.info(f"Message from {msg.telefono}: {msg.texto}")

            # Get history BEFORE saving the current message
            # (brain.py appends the current message, avoiding duplicates)
            historial = await obtener_historial(msg.telefono)

            # Generate reply with Claude
            respuesta = await generar_respuesta(msg.texto, historial)

            # Save the user's message AND the agent's reply to memory
            await guardar_mensaje(msg.telefono, "user", msg.texto)
            await guardar_mensaje(msg.telefono, "assistant", respuesta)

            # Send the reply over WhatsApp via the provider
            await proveedor.enviar_mensaje(msg.telefono, respuesta)

            logger.info(f"Reply to {msg.telefono}: {respuesta}")

        return {"status": "ok"}

    except Exception as e:
        logger.error(f"Webhook error: {e}")
        raise HTTPException(status_code=500, detail=str(e))
