# agent/main.py — FastAPI server + WhatsApp webhook
# Generated by AgentKit

"""
Main server for the WhatsApp agent.
Works with any provider (Meta, Twilio) thanks to the providers layer.
"""

import os
import logging
from contextlib import asynccontextmanager
from fastapi import FastAPI, Request, HTTPException
from fastapi.responses import PlainTextResponse
from dotenv import load_dotenv

from agent.brain import generate_reply
from agent.memory import init_db, save_message, get_history
from agent.providers import get_provider

load_dotenv()

# Logging configuration depending on environment
ENVIRONMENT = os.getenv("ENVIRONMENT", "development")
log_level = logging.DEBUG if ENVIRONMENT == "development" else logging.INFO
logging.basicConfig(level=log_level)
logger = logging.getLogger("agentkit")

# WhatsApp provider (configured in .env via WHATSAPP_PROVIDER)
provider = get_provider()
PORT = int(os.getenv("PORT", 8000))


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Initialize the database when the server starts."""
    await init_db()
    logger.info("Database initialized")
    logger.info(f"AgentKit server running on port {PORT}")
    logger.info(f"WhatsApp provider: {provider.__class__.__name__}")
    yield


app = FastAPI(
    title="AgentKit — WhatsApp AI Agent",
    version="1.0.0",
    lifespan=lifespan
)


@app.get("/")
async def health_check():
    """Health endpoint for Railway/monitoring."""
    return {"status": "ok", "service": "agentkit"}


@app.get("/webhook")
async def webhook_verification(request: Request):
    """GET webhook verification (required by Meta Cloud API, no-op for others)."""
    result = await provider.validate_webhook(request)
    if result is not None:
        return PlainTextResponse(str(result))
    return {"status": "ok"}


@app.post("/webhook")
async def webhook_handler(request: Request):
    """
    Receives WhatsApp messages via the configured provider.
    Processes the message, generates a reply with the model, and sends it back.
    """
    try:
        # Parse webhook — the provider normalizes the format
        messages = await provider.parse_webhook(request)

        for msg in messages:
            # Ignore own or empty messages
            if msg.is_own or not msg.text:
                continue

            logger.info(f"Message from {msg.phone}: {msg.text}")

            # Get history BEFORE saving the current message
            # (brain.py appends the current message, avoiding duplicates)
            history = await get_history(msg.phone)

            # Generate reply with the model
            reply = await generate_reply(msg.text, history)

            # Save the user's message AND the agent's reply to memory
            await save_message(msg.phone, "user", msg.text)
            await save_message(msg.phone, "assistant", reply)

            # Send the reply over WhatsApp via the provider
            await provider.send_message(msg.phone, reply)

            logger.info(f"Reply to {msg.phone}: {reply}")

        return {"status": "ok"}

    except Exception as e:
        logger.error(f"Webhook error: {e}")
        raise HTTPException(status_code=500, detail=str(e))
