# agent/memory.py — Conversation memory with SQLite
# Generated by AgentKit

"""
The agent's memory system. Stores conversation history per phone number
using SQLite (local) or PostgreSQL (production).
"""

import os
from datetime import datetime
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession, async_sessionmaker
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy import String, Text, DateTime, select, Integer
from dotenv import load_dotenv

load_dotenv()

# Database configuration
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite+aiosqlite:///./agentkit.db")

# If it's PostgreSQL in production, adjust the URL scheme
if DATABASE_URL.startswith("postgresql://"):
    DATABASE_URL = DATABASE_URL.replace("postgresql://", "postgresql+asyncpg://", 1)

engine = create_async_engine(DATABASE_URL, echo=False)
async_session = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)


class Base(DeclarativeBase):
    pass


class Message(Base):
    """Message model in the database."""
    __tablename__ = "messages"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    phone: Mapped[str] = mapped_column(String(50), index=True)
    role: Mapped[str] = mapped_column(String(20))  # "user" or "assistant"
    content: Mapped[str] = mapped_column(Text)
    timestamp: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)


async def init_db():
    """Create tables if they don't exist."""
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)


async def save_message(phone: str, role: str, content: str):
    """Save a message to the conversation history."""
    async with async_session() as session:
        message = Message(
            phone=phone,
            role=role,
            content=content,
            timestamp=datetime.utcnow()
        )
        session.add(message)
        await session.commit()


async def get_history(phone: str, limit: int = 20) -> list[dict]:
    """
    Retrieve the last N messages of a conversation.

    Args:
        phone: The customer's phone number
        limit: Max number of messages to retrieve (default: 20)

    Returns:
        List of dicts with role and content
    """
    async with async_session() as session:
        query = (
            select(Message)
            .where(Message.phone == phone)
            .order_by(Message.timestamp.desc())
            .limit(limit)
        )
        result = await session.execute(query)
        messages = list(result.scalars().all())

        # Reverse for chronological order (most recent come first)
        messages.reverse()

        return [
            {"role": msg.role, "content": msg.content}
            for msg in messages
        ]


async def clear_history(phone: str):
    """Delete all history of a conversation."""
    async with async_session() as session:
        query = select(Message).where(Message.phone == phone)
        result = await session.execute(query)
        messages = result.scalars().all()
        for msg in messages:
            await session.delete(msg)
        await session.commit()
