# agent/tools.py — Agent tools
# Generated by AgentKit

"""
Business-specific tools.
These functions extend the agent's capabilities beyond replying with text.
Generated for Arab world's use cases: FAQ, appointments, leads/sales,
orders, and post-sale support.
"""

import os
import yaml
import logging
import uuid
from datetime import datetime

logger = logging.getLogger("agentkit")


def load_business_info() -> dict:
    """Load business information from business.yaml."""
    try:
        with open("config/business.yaml", "r", encoding="utf-8") as f:
            return yaml.safe_load(f)
    except FileNotFoundError:
        logger.error("config/business.yaml not found")
        return {}


def get_business_hours() -> dict:
    """Return the business hours. Arab world is open 24/7."""
    info = load_business_info()
    return {
        "hours": info.get("business", {}).get("hours", "Open 24/7"),
        "is_open": True,  # Arab world is always open
    }


def search_knowledge(query: str) -> str:
    """
    Search for relevant information in the /knowledge files.
    Returns the most relevant content found.
    """
    results = []
    knowledge_dir = "knowledge"

    if not os.path.exists(knowledge_dir):
        return "No knowledge files available."

    for file_name in os.listdir(knowledge_dir):
        path = os.path.join(knowledge_dir, file_name)
        if file_name.startswith(".") or not os.path.isfile(path):
            continue
        try:
            with open(path, "r", encoding="utf-8") as f:
                content = f.read()
                # Simple text-match search
                if query.lower() in content.lower():
                    results.append(f"[{file_name}]: {content[:500]}")
        except (UnicodeDecodeError, IOError):
            continue

    if results:
        return "\n---\n".join(results)
    return "I couldn't find specific information about that in my files."


# ════════════════════════════════════════════════════════════
# Use-case specific tools for Arab world.
# These are in-memory stubs — wire them up to a real database,
# calendar, or e-commerce backend as the business grows.
# ════════════════════════════════════════════════════════════

# Simple in-memory stores (replace with a real DB in production)
_appointments: dict[str, list[dict]] = {}
_leads: dict[str, dict] = {}
_carts: dict[str, list[dict]] = {}
_tickets: dict[str, dict] = {}


# ── Appointments / reservations ─────────────────────────────
def book_appointment(phone: str, date: str, time: str, reason: str = "styling consultation") -> dict:
    """Book an appointment/reservation for a customer."""
    appointment = {
        "id": str(uuid.uuid4())[:8],
        "date": date,
        "time": time,
        "reason": reason,
        "status": "confirmed",
        "created": datetime.utcnow().isoformat(),
    }
    _appointments.setdefault(phone, []).append(appointment)
    logger.info(f"Appointment booked for {phone}: {appointment['id']}")
    return appointment


def cancel_appointment(phone: str, appointment_id: str) -> bool:
    """Cancel a previously booked appointment."""
    appointments = _appointments.get(phone, [])
    for appointment in appointments:
        if appointment["id"] == appointment_id:
            appointment["status"] = "cancelled"
            return True
    return False


# ── Leads & sales ───────────────────────────────────────────
def register_lead(phone: str, name: str, interest: str) -> dict:
    """Register a sales lead so the team can follow up."""
    lead = {
        "phone": phone,
        "name": name,
        "interest": interest,
        "status": "new",
        "created": datetime.utcnow().isoformat(),
    }
    _leads[phone] = lead
    logger.info(f"Lead registered: {phone} — {interest}")
    return lead


def escalate_to_salesperson(phone: str, context: str) -> dict:
    """Flag a conversation so a human salesperson can take over."""
    logger.info(f"Escalated to salesperson: {phone} — {context}")
    return {"phone": phone, "context": context, "status": "escalated"}


# ── Orders ──────────────────────────────────────────────────
def add_to_cart(phone: str, product: str, size: str, quantity: int = 1) -> list[dict]:
    """Add an item (with size) to the customer's cart."""
    item = {"product": product, "size": size, "quantity": quantity}
    _carts.setdefault(phone, []).append(item)
    return _carts[phone]


def view_cart(phone: str) -> list[dict]:
    """Return the current items in the customer's cart."""
    return _carts.get(phone, [])


def confirm_order(phone: str, shipping_address: str) -> dict:
    """Confirm the order with the cart contents and a shipping address."""
    items = _carts.get(phone, [])
    order = {
        "id": str(uuid.uuid4())[:8],
        "items": items,
        "shipping_address": shipping_address,
        "status": "confirmed",
        "created": datetime.utcnow().isoformat(),
    }
    _carts[phone] = []  # empty the cart after confirming
    logger.info(f"Order confirmed for {phone}: {order['id']}")
    return order


# ── Post-sale support ───────────────────────────────────────
def create_ticket(phone: str, issue: str) -> dict:
    """Create a post-sale support ticket."""
    ticket = {
        "id": str(uuid.uuid4())[:8],
        "phone": phone,
        "issue": issue,
        "status": "open",
        "created": datetime.utcnow().isoformat(),
    }
    _tickets[ticket["id"]] = ticket
    logger.info(f"Support ticket created: {ticket['id']}")
    return ticket


def get_ticket(ticket_id: str) -> dict:
    """Look up the status of a support ticket."""
    return _tickets.get(ticket_id, {"error": "Ticket not found"})
