# agent/tools.py — Agent tools
# Generated by AgentKit

"""
Business-specific tools.
These functions extend the agent's capabilities beyond replying with text.
Generated for Arab world's use cases: FAQ, appointments, leads/sales,
orders, and post-sale support.
"""

import os
import yaml
import logging
import uuid
from datetime import datetime

logger = logging.getLogger("agentkit")


def cargar_info_negocio() -> dict:
    """Load business information from business.yaml."""
    try:
        with open("config/business.yaml", "r", encoding="utf-8") as f:
            return yaml.safe_load(f)
    except FileNotFoundError:
        logger.error("config/business.yaml not found")
        return {}


def obtener_horario() -> dict:
    """Return the business hours. Arab world is open 24/7."""
    info = cargar_info_negocio()
    return {
        "horario": info.get("negocio", {}).get("horario", "Open 24/7"),
        "esta_abierto": True,  # Arab world is always open
    }


def buscar_en_knowledge(consulta: str) -> str:
    """
    Search for relevant information in the /knowledge files.
    Returns the most relevant content found.
    """
    resultados = []
    knowledge_dir = "knowledge"

    if not os.path.exists(knowledge_dir):
        return "No knowledge files available."

    for archivo in os.listdir(knowledge_dir):
        ruta = os.path.join(knowledge_dir, archivo)
        if archivo.startswith(".") or not os.path.isfile(ruta):
            continue
        try:
            with open(ruta, "r", encoding="utf-8") as f:
                contenido = f.read()
                # Simple text-match search
                if consulta.lower() in contenido.lower():
                    resultados.append(f"[{archivo}]: {contenido[:500]}")
        except (UnicodeDecodeError, IOError):
            continue

    if resultados:
        return "\n---\n".join(resultados)
    return "I couldn't find specific information about that in my files."


# ════════════════════════════════════════════════════════════
# Use-case specific tools for Arab world.
# These are in-memory stubs — wire them up to a real database,
# calendar, or e-commerce backend as the business grows.
# ════════════════════════════════════════════════════════════

# Simple in-memory stores (replace with a real DB in production)
_citas: dict[str, list[dict]] = {}
_leads: dict[str, dict] = {}
_carritos: dict[str, list[dict]] = {}
_tickets: dict[str, dict] = {}


# ── Appointments / reservations ─────────────────────────────
def reservar_cita(telefono: str, fecha: str, hora: str, motivo: str = "styling consultation") -> dict:
    """Book an appointment/reservation for a customer."""
    cita = {
        "id": str(uuid.uuid4())[:8],
        "fecha": fecha,
        "hora": hora,
        "motivo": motivo,
        "estado": "confirmed",
        "creada": datetime.utcnow().isoformat(),
    }
    _citas.setdefault(telefono, []).append(cita)
    logger.info(f"Appointment booked for {telefono}: {cita['id']}")
    return cita


def cancelar_cita(telefono: str, cita_id: str) -> bool:
    """Cancel a previously booked appointment."""
    citas = _citas.get(telefono, [])
    for cita in citas:
        if cita["id"] == cita_id:
            cita["estado"] = "cancelled"
            return True
    return False


# ── Leads & sales ───────────────────────────────────────────
def registrar_lead(telefono: str, nombre: str, interes: str) -> dict:
    """Register a sales lead so the team can follow up."""
    lead = {
        "telefono": telefono,
        "nombre": nombre,
        "interes": interes,
        "estado": "new",
        "creado": datetime.utcnow().isoformat(),
    }
    _leads[telefono] = lead
    logger.info(f"Lead registered: {telefono} — {interes}")
    return lead


def escalar_a_vendedor(telefono: str, contexto: str) -> dict:
    """Flag a conversation so a human salesperson can take over."""
    logger.info(f"Escalated to salesperson: {telefono} — {contexto}")
    return {"telefono": telefono, "contexto": contexto, "estado": "escalated"}


# ── Orders ──────────────────────────────────────────────────
def agregar_al_carrito(telefono: str, producto: str, talla: str, cantidad: int = 1) -> list[dict]:
    """Add an item (with size) to the customer's cart."""
    item = {"producto": producto, "talla": talla, "cantidad": cantidad}
    _carritos.setdefault(telefono, []).append(item)
    return _carritos[telefono]


def ver_carrito(telefono: str) -> list[dict]:
    """Return the current items in the customer's cart."""
    return _carritos.get(telefono, [])


def confirmar_pedido(telefono: str, direccion_envio: str) -> dict:
    """Confirm the order with the cart contents and a shipping address."""
    items = _carritos.get(telefono, [])
    pedido = {
        "id": str(uuid.uuid4())[:8],
        "items": items,
        "direccion_envio": direccion_envio,
        "estado": "confirmed",
        "creado": datetime.utcnow().isoformat(),
    }
    _carritos[telefono] = []  # empty the cart after confirming
    logger.info(f"Order confirmed for {telefono}: {pedido['id']}")
    return pedido


# ── Post-sale support ───────────────────────────────────────
def crear_ticket(telefono: str, problema: str) -> dict:
    """Create a post-sale support ticket."""
    ticket = {
        "id": str(uuid.uuid4())[:8],
        "telefono": telefono,
        "problema": problema,
        "estado": "open",
        "creado": datetime.utcnow().isoformat(),
    }
    _tickets[ticket["id"]] = ticket
    logger.info(f"Support ticket created: {ticket['id']}")
    return ticket


def consultar_ticket(ticket_id: str) -> dict:
    """Look up the status of a support ticket."""
    return _tickets.get(ticket_id, {"error": "Ticket not found"})
